In [2]:
import pandas as pd 
import numpy as np
import requests
# from config import omdb_api
from pprint import pprint

pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [3]:
books = pd.read_csv("../../br.csv/br.csv", encoding="utf-8", engine="python", error_bad_lines=False)

Skipping line 312075: unexpected end of data

In [4]:
more_reviews = books.drop(books[books.ratingsCount < 100000].index)

In [5]:
more_reviews['title'].nunique()

3413

In [6]:
sample = more_reviews.iloc[0:2000]
sample = sample.reset_index()
book_rating = sample[['rating']]

In [7]:
books = []

for index, row in sample.iterrows():
    title = row['title']
    books.append(title)

In [10]:
base_url = "http://www.omdbapi.com/?" 

query_url = f"{base_url}apikey=trilogy&t={books[0]}"

response = requests.get(query_url)

pprint(response.json())

{'Actors': 'Richard Harris, Maggie Smith, Robbie Coltrane, Saunders Triplets',
 'Awards': 'Nominated for 3 Oscars. Another 17 wins & 62 nominations.',
 'BoxOffice': '$317,557,891',
 'Country': 'UK, USA',
 'DVD': '28 May 2002',
 'Director': 'Chris Columbus',
 'Genre': 'Adventure, Family, Fantasy',
 'Language': 'English',
 'Metascore': '64',
 'Plot': 'An orphaned boy enrolled in a school of wizardry, where he learns '
         'the truth about himself, his family and the terrible evil that '
         'haunts the magical world.',
 'Poster': 'https://m.media-amazon.com/images/M/MV5BNjQ3NWNlNmQtMTE5ZS00MDdmLTlkZjUtZTBlM2UxMGFiMTU3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg',
 'Production': 'Warner Bros. Pictures',
 'Rated': 'PG',
 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.6/10'},
             {'Source': 'Rotten Tomatoes', 'Value': '80%'},
             {'Source': 'Metacritic', 'Value': '64/100'}],
 'Released': '16 Nov 2001',
 'Response': 'True',
 'Runtime': '152 min',
 'Title': "Harry Potter and the Sorcerer's Stone",
 'Type': 'movie',
 'Website': 'http://movies.warnerbros.com/awards/harry.html',
 'Writer': 'J.K. Rowling (novel), Steve Kloves (screenplay)',
 'Year': '2001',
 'imdbID': 'tt0241527',
 'imdbRating': '7.6',
 'imdbVotes': '538,048'}

In [11]:
json_list = []

for book in books:
    try:
        query_url= base_url + "apikey=" + "trilogy" + "&t=" + book
        response = requests.get(query_url)
        data = response.json()
        json_list.append(data)
        
    except:
        print("...")

In [12]:
# pprint(json_list)

In [56]:
df = pd.DataFrame(json_list)
df['Book Rating'] = book_rating
df

,Actors,Awards,BoxOffice,Country,DVD,Director,Error,Genre,Language,Metascore,...,Title,Type,Website,Writer,Year,imdbID,imdbRating,imdbVotes,totalSeasons,Book Rating
0,"Richard Harris, Maggie Smith, Robbie Coltrane,...",Nominated for 3 Oscars. Another 17 wins & 62 n...,"$317,557,891","UK, USA",28 May 2002,Chris Columbus,NaN,"Adventure, Family, Fantasy",English,64,...,Harry Potter and the Sorcerer's Stone,movie,http://movies.warnerbros.com/awards/harry.html,"J.K. Rowling (novel), Steve Kloves (screenplay)",2001,tt0241527,7.6,"538,048",NaN,4.440
1,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.540
2,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.470
3,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.380
4,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.530
5,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.530
6,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.750
7,"Michaela Badinková, Jerzy Michal Bozyk, Igor C...",4 wins & 8 nominations.,N/A,"Czech Republic, Poland, France",N/A,Petr Zelenka,NaN,Drama,"Czech, Polish, English",N/A,...,The Karamazov Brothers,movie,http://www.braciakaramazow.pl/,"Fyodor Dostoevsky (novel), Evald Schorm (stage...",2008,tt1080716,7.8,989,NaN,4.310
8,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.910
9,"Keir Dullea, Gary Lockwood, William Sylvester,...",Won 1 Oscar. Another 13 wins & 10 nominations.,"$135,620","UK, USA",25 Aug 1998,Stanley Kubrick,NaN,"Adventure, Sci-Fi","English, Russian",82,...,2001: A Space Odyssey,movie,N/A,"Stanley Kubrick (screenplay), Arthur C. Clarke...",1968,tt0062622,8.3,"516,610",NaN,3.730
10,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.930
11,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.930
12,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.930
13,"Robert Blake, Scott Wilson, John Forsythe, Pau...",Nominated for 4 Oscars. Another 4 wins & 5 nom...,N/A,USA,23 Sep 2003,Richard Brooks,NaN,"Biography, Crime, Drama",English,89,...,In Cold Blood,movie,N/A,"Truman Capote (based on the book by), Richard ...",1967,tt0061809,8.0,"21,471",NaN,4.050
14,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.040
15,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.300
16,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.300
17,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.300
18,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.180
19,"Bobby Driscoll, Robert Newton, Basil Sydney, W...",1 nomination.,N/A,"UK, USA",25 Apr 2006,Byron Haskin,NaN,"Adventure, Family",English,N/A,...,Treasure Island,movie,N/A,"Lawrence Edward Watkin (screenplay), Robert Lo...",1950,tt0043067,7.0,"5,697",NaN,3.820
20,"Bobby Driscoll, Robert Newton, Basil Sydney, W...",1 nomination.,N/A,"UK, USA",25 Apr 2006,Byron Haskin,NaN,"Adventure, Family",English,N/A,...,Treasure Island,movie,N/A,"Lawrence Edward Watkin (screenplay), Robert Lo...",1950,tt0043067,7.0,"5,697",NaN,3.820
21,"Bobby Driscoll, Robert Newton, Basil Sydney, W...",1 nomination.,N/A,"UK, USA",25 Apr 2006,Byron Haskin,NaN,"Adventure, Family",English,N/A,...,Treasure Island,movie,N/A,"Lawrence Edward Watkin (screenplay), Robert Lo...",1950,tt0043067,7.0,"5,697",NaN,3.820
22,"Bobby Driscoll, Robert Newton, Basil Sydney, W...",1 nomination.,N/A,"UK, USA",25 Apr 2006,Byron Haskin,NaN,"Adventure, Family",English,N/A,...,Treasure Island,movie,N/A,"Lawrence Edward Watkin (screenplay), Robert Lo...",1950,tt0043067,7.0,"5,697",NaN,3.820
23,"Bobby Driscoll, Robert Newton, Basil Sydney, W...",1 nomination.,N/A,"UK, USA",25 Apr 2006,Byron Haskin,NaN,"Adventure, Family",English,N/A,...,Treasure Island,movie,N/A,"Lawrence Edward Watkin (screenplay), Robert Lo...",1950,tt0043067,7.0,"5,697",NaN,3.820
24,N/A,N/A,N/A,USA,N/A,N/A,NaN,N/A,English,N/A,...,The Catcher in the Rye,movie,N/A,N/A,2008,tt1206286,2.1,632,NaN,3.790
25,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.190
26,"Shane West, Mandy Moore, Peter Coyote, Daryl H...",4 wins & 2 nominations.,"$41,090,572",USA,09 Jul 2002,Adam Shankman,NaN,"Drama, Romance",English,35,...,A Walk to Remember,movie,http://awalktoremember.warnerbros.com,"Nicholas Sparks (novel), Karen Janszen (screen...",2002,tt0281358,7.4,"182,839",NaN,4.150
27,"Kevin Costner, Robin Wright, Paul Newman, John...",6 nominations.,N/A,USA,03 Aug 1999,Luis Mandoki,NaN,"Drama, Romance",English,39,...,Message in a Bottle,movie,N/A,"Nicholas Sparks (novel), Gerald Di Pego (scree...",1999,tt0139462,6.2,"32,381",NaN,3.950
28,"Tim Ivey, Gena Rowlands, Starletta DuPois, Jam...",12 wins & 10 nominations.,"$81,000,000",USA,08 Feb 2005,Nick Cassavetes,NaN,"Drama, Romance",English,53,...,The Notebook,movie,http://www.thenotebookmovie.com/,"Jeremy Leven (screenplay), Jan Sardi (adaptati...",2004,tt0332280,7.9,"453,407",NaN,4.070
29,Gustavo Alonso,N/A,N/A,Uruguay,N/A,Pablo Moreira,NaN,"Short, Horror",Spanish,N/A,...,El Guardián,movie,N/A,"Pablo Moreira, Siraco",2016,tt5698306,N/A,N/A,NaN,4.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,"Sam Neill, Laura Dern, Jeff Goldblum, Richard ...",Won 3 Oscars. Another 32 wins & 25 nominations.,"$45,299,680",USA,10 Oct 2000,Steven Spielberg,NaN,"Adventure, Sci-Fi, Thriller","English, Spanish",68,...,Jurassic Park,movie,http://www.jurassicpark.com/maingate_flash.html,"Michael Crichton (novel), Michael Crichton (sc...",1993,tt0107290,8.1,"747,324",NaN,3.970
1971,"Sam Neill, Laura Dern, Jeff Goldblum, Richard ...",Won 3 Oscars. Another 32 wins & 25 nominations.,"$45,299,680",USA,10 Oct 2000,Steven Spielberg,NaN,"Adventure, Sci-Fi, Thriller","English, Spanish",68,...,Jurassic Park,movie,http://www.jurassicpark.com/maingate_flash.html,"Michael Crichton (novel), Michael Crichton (sc...",1993,tt0107290,8.1,"747,324",NaN,3.970
1972,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.870
1973,"Sam Neill, Laura Dern, Jeff Goldblum, Richard ...",Won 3 Oscars. Another 32 wins & 25 nominations.,"$45,299,680",USA,10 Oct 2000,Steven Spielberg,NaN,"Adventure, Sci-Fi, Thriller","English, Spanish",68,...,Jurassic Park,movie,http://www.jurassicpark.com/maingate_flash.html,"Michael Crichton (novel), Michael Crichton (sc...",1993,tt0107290,8.1,"747,324",NaN,3.970
1974,"Alexa Davalos, Luke Kleintank, DJ Qualls, Joel...",Won 2 Primetime Emmys. Another 4 wins & 31 nom...,NaN,USA,NaN,N/A,NaN,"Drama, Sci-Fi, Thriller","English, German, Japanese",N/A,...,The Man in the High Castle,series,NaN,Frank Spotnitz,2015–,tt1740299,8.1,"57,947",4,3.660
1975,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.160
1976,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.430
1977,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.430
1978,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.430
1979,"Marlon Brando, Al Pacino, James Caan, Richard ...",Won 3 Oscars. Another 24 wins & 28 nominations.,N/A,USA,09 Oct 2001,Francis Ford Coppola,NaN,"Crime, Drama","English, Italian, Latin",100,...,The Godfather,movie,http://www.thegodfather.com,"Mario Puzo (screenplay by), Francis Ford Coppo...",1972,tt0068646,9.2,"1,370,696",NaN,4.360
1980,"Marlon Brando, Al Pacino, James Caan, Richard ...",Won 3 Oscars. Another 24 wins & 28 nominations.,N/A,USA,09 Oct 2001,Francis Ford Coppola,NaN,"Crime, Drama","English, Italian, Latin",100,...,The Godfather,movie,http://www.thegodfather.com,"Mario Puzo (screenplay by), Francis Ford Coppo...",1972,tt0068646,9.2,"1,370,696",NaN,4.360
1981,N/A,N/A,NaN,USA,NaN,N/A,NaN,Animation,N/A,N/A,...,Green Eggs and Ham,series,NaN,N/A,2018–,tt4651448,N/A,N/A,N/A,4.290
1982,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.080
1983,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.830
1984,"Ewan McGregor, Ewen Bremner, Jonny Lee Miller,...",Nominated for 1 Oscar. Another 23 wins & 33 no...,N/A,UK,24 Mar 1998,Danny Boyle,NaN,Drama,English,83,...,Trainspotting,movie,http://www.miramax.com/movie/trainspotting/,"Irvine Welsh (based on the novel by), John Hod...",1996,tt0117951,8.2,"568,705",NaN,4.080
1985,"Ewan McGregor, Ewen Bremner, Jonny Lee Miller,...",Nominated for 1 Oscar. Another 23 wins & 33 no...,N/A,UK,24 Mar 1998,Danny Boyle,NaN,Drama,English,83,...,Trainspotting,movie,http://www.miramax.com/movie/trainspotting/,"Irvine Welsh (based on the novel by), John Hod...",1996,tt0117951,8.2,"568,705",NaN,4.080
1986,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.890
1987,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.890
1988,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.040
1989,"Jean-Jacques Annaud, Norbert Iborra, Valentina...",N/A,N/A,France,N/A,"Sédrik Allani, Julien Godinger",NaN,Documentary,French,N/A,...,Le nom de la rose,movie,N/A,N/A,2004,tt1700488,8.0,9,NaN,4.110
1990,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.110
1991,"Sean Connery, Christian Slater, Helmut Qualtin...",Won 2 BAFTA Film Awards. Another 15 wins & 5 n...,N/A,"Italy, France, West Germany",06 Jul 2004,Jean-Jacques Annaud,NaN,"Crime, Drama, Mystery","English, Latin",N/A,...,The Name of the Rose,movie,N/A,"Umberto Eco (novel), Andrew Birkin (screenplay...",1986,tt0091605,7.8,"91,544",NaN,4.110
1992,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.040
1993,"Annette Bening, Brian Cox, Joseph Fiennes, Eva...",Nominated for 1 Golden Globe. Another 3 wins &...,"$6,754,898",USA,29 Jul 2003,Ryan Murphy,NaN,"Comedy, Drama",English,52,...,Running with Scissors,movie,http://www.sonypictures.com/movies/runningwith...,"Ryan Murphy (screenplay), Augusten Burroughs (...",2006,tt0439289,6.2,"21,025",NaN,3.700
1994,"Annette Bening, Brian Cox, Joseph Fiennes, Eva...",Nominated for 1 Golden Globe. Another 3 wins &...,"$6,754,898",USA,29 Jul 2003,Ryan Murphy,NaN,"Comedy, Drama",English,52,...,Running with Scissors,movie,http://www.sonypictures.com/movies/runningwith...,"Ryan Murphy (screenplay), Augusten Burroughs (...",2006,tt0439289,6.2,"21,025",NaN,3.700
1995,"Jodie Foster, Lawrence A. Bonney, Kasi Lemmons...",Won 5 Oscars. Another 54 wins & 44 nominations.,N/A,USA,01 Jul 1998,Jonathan Demme,NaN,"Crime, Drama, Thriller",English,85,...,The Silence of the Lambs,movie,N/A,"Thomas Harris (novel), Ted Tally (screenplay)",1991,tt0102926,8.6,"1,069,146",NaN,4.140
1996,NaN,NaN,NaN,NaN,NaN,NaN,Movie not found!,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.370
1997,"Balthazar Getty, Chris Furrh, Danuel Pipoly, J...",3 nominations.,N/A,USA,20 Nov 2001,Harry Hook,NaN,"Adventure, Drama, Thriller",English,N/A,...,Lord of the Flies,movie,N/A,"William Golding (novel), Jay Presson Allen (sc...",1990,tt0100054,6.4,"24,942",NaN,3.650
1998,"Balthazar Getty, Chris Furrh, Danuel Pipoly, J...",3 nominations.,N/A,USA,20 Nov 2001,Harry Hook,NaN,"Adventure, Drama, Thriller",English,N/A,...,Lord of the Flies,movie,N/A,"William Golding (novel), Jay Presson Allen (sc...",1990,tt0100054,6.4,"24,942",NaN,3.650
1999,"Robert Ginty, Lucinda Dooling, John Sanderford...",N/A,N/A,USA,N/A,Charles Band,NaN,Horror,English,N/A,...,The Alchemist,movie,N/A,Alan J. Adler (screenplay),1983,tt0088691,3.8,411,NaN,3.820

In [57]:
df.columns

Index(['Actors', 'Awards', 'BoxOffice', 'Country', 'DVD', 'Director', 'Error',
       'Genre', 'Language', 'Metascore', 'Plot', 'Poster', 'Production',
       'Rated', 'Ratings', 'Released', 'Response', 'Runtime', 'Title', 'Type',
       'Website', 'Writer', 'Year', 'imdbID', 'imdbRating', 'imdbVotes',
       'totalSeasons', 'Book Rating'],
      dtype='object')

In [58]:
by_dir= df[['Title','Director','Book Rating', 'imdbRating']]
by_dir['Book Rating'] = by_dir['Book Rating']*2

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [62]:
by_dir = by_dir.replace('N/A', np.nan)
by_dir = by_dir.dropna()

In [63]:
by_dir['imdbRating'] = by_dir['imdbRating'].astype(float)

In [64]:
by_dir = by_dir.reset_index()

In [65]:
by_dir = by_dir.drop(columns=['index'])

In [66]:
final_df = by_dir.groupby('Director').mean()

In [67]:
final_df

                                                    Book Rating  imdbRating
Director
Adam Shankman                                             8.300       7.400
Adrian Shergold                                           8.260       7.600
Agnieszka Holland                                         8.240       7.300
Aki Kaurismäki                                            8.380       7.200
Alan Parker                                               8.160       7.300
Alan Rudolph                                              8.160       4.600
Albert Lewin                                              8.120       7.600
Aleksi Vettenranta                                        7.660       6.100
Alfonso Arau                                              7.880       7.200
Alfonso Cuarón                                            7.580       6.882
Alfred Hitchcock                                          8.420       8.100
Allan Dwan                                                7.940       7.300
Andrej Kosak                                              7.920       8.100
Andrew Adamson                                            8.380       6.900
Andrew Davis                                              8.280       6.900
Andrew L. Stone                                           7.340       6.200
Andy Muschietti                                           8.380       7.400
Ang Lee                                                   7.940       7.800
Anna Boden, Ryan Fleck                                    8.280       7.100
Anthony Minghella                                         7.660       7.200
Ari Mark                                                  7.560       3.900
Barbra Streisand                                          8.440       6.700
Baz Luhrmann                                              7.780       7.300
Bille August                                              8.400       6.900
Blake Edwards                                             7.780       7.700
Brian De Palma                                            7.860       7.400
Brian Percival                                            8.720       7.600
Byron Haskin                                              7.630       7.050
Caroline Thompson                                         7.880       6.600
Cary Joji Fukunaga                                        8.200       7.400
...                                                         ...         ...
Steven Spielberg                                          8.308       7.653
Sédrik Allani, Julien Godinger                            8.220       8.000
Taylor Hackford                                           7.620       7.400
Terence H. Winkless                                       8.060       5.400
Terry Gilliam                                             8.160       7.700
Theo Kerp                                                 8.560       7.900
Thom Andersen                                             7.720       8.000
Tim Burton                                                8.060       6.500
Tobe Hooper                                               7.980       6.800
Tod Browning                                              7.960       7.600
Tod Williams                                              7.280       4.300
Tom Dallis                                                8.620       4.400
Tom Holland                                               7.340       5.700
Tom Tykwer                                                8.000       7.500
Tom Tykwer, Lana Wachowski, Lilly Wachowski               8.020       7.500
Tran Anh Hung                                             8.040       6.400
Travis Neal                                               8.580       5.300
Ulu Grosbard                                              7.680       6.400
Vadim Perelman                                            7.660       7.600
Victor Cook, Mike Disa, Sang-Jin Kim, Shûkô Mur...        7.980       6.600
Victor Fleming, George Cukor, Sam Wood                    8.560       8.200
Volker Schlöndorff                                        6.980       7.300
Walter D. Asmus                                           7.620       6.300
Walter Salles                                             7.280       6.100
Wayne Wang                                                7.860       7.300
Werner Herzog                                             7.980       7.200
William Desmond Taylor                                    8.980       4.100
William Sterling                                          8.120       5.800
William Wyler                                             7.640       7.700
Wojciech Smarzowski                                       7.960       7.800

[277 rows x 2 columns]

In [52]:
final_df.to_csv('output/sorted_by_rated.csv')